### ISSUE TITLE
Build instructions fail

### ISSUE THREAD

**Issue by glattercj** [patsec/ot-sim#5]
Following the current build instructions in the README fails at the `sudo make -C src/go install` step (tried both 20.04 and 22.04): 
<img width="795" alt="Screenshot 2024-03-21 at 07 44 16" src="https://github.com/patsec/ot-sim/assets/8338736/941caf49-4d88-476c-ae01-91f345237431">

Looks like the issue is with using an older version of Golang. I tested with 1.21.8 and it works fine. Will submit a PR to update the README.

**Comment by Astarry** [comment]
Probably need to update the go.mod file as well, if required minimum golang version > 1.18

**Comment by glattercj** [comment]
Thanks @Astarry, I updated the PR.
