### ISSUE TITLE
Launching Backplane module crashes/closes I/O Module

### ISSUE THREAD

**Issue by SleepyHIpster** [patsec/ot-sim#7]
Using HELICS Version 3.4.0

When an I/O module is running, if a Backplane module is started, the I/O module closes. This occurs whether or not the modules are started separately or with a CPU module.

The logs show that the IO-Module successfully sets up its federate and reads its pub/sub lists before exiting.

**Comment by activeshadow** [comment]
Hi @SleepyHIpster, we can look into this further, but we'll need some additional details. Can you provide a config file (or files) we can use to reproduce, as well as some captured logs from a session where you're experiencing this issue?

**Comment by SleepyHIpster** [comment]
Here are my setup and log files. The whole thing can be run with `helics run --path=transformer_launcher.json` in the folder.
Requires `helics[cli]` to be installed. 

- `transformer.xml` is the io-module
- `tempSensor` is the HELICS federate
- `terminal.log` shows the output in the terminal from the HELICS runner.

It seems that when the message bus is launched first, the IO module does not enter execution mode while if the IO module is started first (as in the logs included) the IO module *does* reach execution but still exits.

[files.zip](https://github.com/patsec/ot-sim/files/15380602/files.zip)

**Comment by SleepyHIpster** [comment]
Despite the example files not using DNP3, downgrading to Ubuntu 20.04 fixed this issue.
